common:
	@sh components/common.sh
frontend: common
	@sh components/frontend.sh
mongo: common
	@sh components/mongo.sh
catalogue: common
	@sh components/catalogue.sh
redis: common
	@sh components/redis.sh
user: common
	@sh components/user.sh
cart: common
	@sh components/cart.sh